# Generated by Django 5.2 on 2025-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('thumbnailUrl', models.CharField(max_length=252)),
                ('pagecount', models.IntegerField(default=0)),
                ('shortDescription', models.CharField(null=True)),
                ('longDescription', models.TextField(null=True)),
            ],
        ),
    ]
