# Generated by Django 5.2 on 2025-04-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
